name: Check PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - id: bump
        name: Match PR Label
        uses: zwaldowski/match-label-action@v3
        with:
          allowed: major,minor,patch

      - uses: zwaldowski/semver-release-action@v3
        with:
          dry_run: true
          bump: ${{ steps.bump.outputs.match }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  comment:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v3
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR
        if: env.WORKFLOW_CONCLUSION == 'failure'
        uses: thollander/actions-comment-pull-request@1.0.2
        with:
          message: "Please apply one of the following labels to the PR: 'patch', 'minor', or 'major'."
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}